export const planningInformation = [
    {
        week: '1 Abril',
        weekEnd: '7 Abril',
        weekCount: '1/13',
        event: '',
        mesociclo: 'Desarrollador',
        microciclo: 'O',
        intensidad: '3 de 6',
        cardio: 'Continuo con intensidades',
        cardioRoutine: `3 sprints de 3" y 3 de 6", Sprint de 10" cada 1" 20", 10 sprints y completar trote total, Trote al 70% alternando con pasos laterales y retrocesos, sprint al 100%`,
        totalTime: '100',
        gym: 'Fuerza sub-maxima',
        gymRoutine: '4 series de 10 repeticiones al 80%, Fase positiva Rapida, fase negativa moderada, Alternar ejercicios (anterior- posterior),30 segundos a 1 min de recuperacion entre series, 3 minutos de recupperacion entre ejercicios, 10 ejercicios por sesion',
        gymRoutineDays: 'Lunes: Pecho, Biceps, Hombro -Martes: Espalda, Triceps, y Trapecio -Miercoles: Pierna y Gluteo -Jueves: Pecho, Biceps y Antebrazo -Viernes: Espalda y Triceps'
    },
    {
        week: '8 Abril',
        weekEnd: '14 Abril',
        weekCount: '2/13',
        event: '',
        mesociclo: 'Desarrollador',
        microciclo: '0',
        intensidad: '4 de 6',
        cardio: 'Continuo con intensidades',
        cardioRoutine: '3 sprints de 3" y 3 de 6", Sprint de 10" cada 1" 20", 10 sprints y completar trote total, Trote al 70% alternando con pasos laterales y retrocesos, sprint al 100%',
        totalTime: '100',
        gym: 'Fuerza sub-maxima',
        gymRoutine: '4 series de 10 repeticiones al 80%, Fase positiva Rapida, fase negativa moderada, Alternar ejercicios (anterior- posterior),30 segundos a 1 min de recuperacion entre series, 3 minutos de recupperacion entre ejercicios, 10 ejercicios por sesion',
        gymRoutineDays: 'Lunes: Pecho, Biceps, Hombro -Martes: Espalda, Triceps, y Trapecio -Miercoles: Pierna y Gluteo -Jueves: Pecho, Biceps y Antebrazo -Viernes: Espalda y Triceps'
    },
    {
        week: '15 Abril',
        weekEnd: '21 Abril',
        weekCount: '3/13',
        event: '',
        mesociclo: 'Desarrollador',
        microciclo: 'CH',
        intensidad: '5 de 6',
        cardio: 'Continuo con intensidades',
        cardioRoutine: '3 sprints de 3" y 3 de 6", Sprint de 5" cada 1", 10 sprints y completar trote total, Trote al 70% alternando con pasos laterales y retrocesos, sprint al 100%',
        totalTime: '90',
        gym: 'Fuerza sub-maxima',
        gymRoutine: '4 series de 10 repeticiones al 80%, Fase positiva Rapida, fase negativa moderada, Alternar ejercicios (anterior- posterior),30 segundos a 1 min de recuperacion entre series, 3 minutos de recupperacion entre ejercicios, 10 ejercicios por sesion',
        gymRoutineDays: 'Lunes: Pecho, Biceps, Hombro -Martes: Espalda, Triceps, y Trapecio -Miercoles: Pierna y Gluteo -Jueves: Pecho, Biceps y Antebrazo -Viernes: Espalda y Triceps'
    },
    {
        week: '22 Abril',
        weekEnd: '28 Abril',
        weekCount: '4/13',
        event: '',
        mesociclo: 'Desarrollador',
        microciclo: 'R',
        intensidad: '2 de 6',
        cardio: 'Continuo con intensidades',
        cardioRoutine: '3 sprints de 3" y 3 de 6", Sprint de 5" cada 1", 10 sprints y completar trote total, Trote al 70% alternando con pasos laterales y retrocesos, sprint al 100%',
        totalTime: '90',
        gym: 'Fuerza maxima',
        gymRoutine: '4 series de 6 repeticiones al 80%, Fase positiva moderada, Fase negativa rapida, Alternar ejercicios (anterior- posterior),1 min de recuperacion entre series, 3 minutos de recuperacion entre ejercicios, 10 ejercicios por sesion',
        gymRoutineDays: 'Lunes: Pecho, Biceps, Hombro -Martes: Espalda, Triceps, y Trapecio -Miercoles: Pierna y Gluteo -Jueves: Pecho, Biceps y Antebrazo -Viernes: Espalda y Triceps -Sabado: Pierna, Gluteo, y Hombro'
    },
    {
        week: '29 Abril',
        weekEnd: '5 Mayo',
        weekCount: '5/13',
        event: '',
        mesociclo: 'Desarrollador',
        microciclo: 'CH',
        intensidad: '5 de 6',
        cardio: 'Continuo con intensidades',
        cardioRoutine: '3 sprints de 3" y 3 de 6", Sprint de 5" cada 1", 10 sprints y completar trote total, Trote al 70% alternando con pasos laterales y retrocesos, sprint al 100%',
        totalTime: '80',
        gym: 'Fuerza maxima',
        gymRoutine: '4 series de 6 repeticiones al 80%, Fase positiva moderada, Fase negativa rapida, Alternar ejercicios (anterior- posterior),1 min de recuperacion entre series, 3 minutos de recuperacion entre ejercicios, 10 ejercicios por sesion',
        gymRoutineDays: 'Lunes: Pecho, Biceps, Hombro -Martes: Espalda, Triceps, y Trapecio -Miercoles: Pierna y Gluteo -Jueves: Pecho, Biceps y Antebrazo -Viernes: Espalda y Triceps -Sabado: Pierna, Gluteo, y Hombro'
    },
    {
        week: '6 Mayo',
        weekEnd: '12 Mayo',
        weekCount: '6/13',
        event: 'Interprepa',
        mesociclo: 'Desarrollador',
        microciclo: 'R',
        intensidad: '3 de 6',
        cardio: 'Interrumpido',
        cardioRoutine: '3 Rounds de 3" (25 trote moderado x 5" de intensidad), 1" de descaso entre rounds caminando, Completar tiempo restante',
        totalTime: '80',
        gym: 'Fuerza maxima',
        gymRoutine: '4 series de 6 repeticiones al 80%, Fase positiva moderada, Fase negativa rapida, Alternar ejercicios (anterior- posterior),1 min de recuperacion entre series, 3 minutos de recuperacion entre ejercicios, 10 ejercicios por sesion',
        gymRoutineDays: 'Lunes: Pecho, Biceps, Hombro -Martes: Espalda, Triceps, y Trapecio -Miercoles: Pierna y Gluteo -Jueves: Pecho, Biceps y Antebrazo -Viernes: Espalda y Triceps -Sabado: Pierna, Gluteo, y Hombro'
    },
    {
        week: '13 Mayo',
        weekEnd: '19 Mayo',
        weekCount: '7/13',
        event: 'IMSS',
        mesociclo: 'Pre-Competitivo',
        microciclo: 'O',
        intensidad: '3 de 6',
        cardio: 'Interrumpido',
        cardioRoutine: '3 Rounds de 3" (25 trote moderado x 5" de intensidad), 1" de descaso entre rounds caminando, Completar tiempo restante',
        totalTime: '80',
        gym: 'Fuerza sub-maxima',
        gymRoutine: '4 series de 12 repeticiones al 80%, Fase positiva moderada, Fase negativa rapida, Alternar ejercicios (anterior - posterior),30 seg - 1 min de recuperacion entre series, 1 - 3 minutos de recuperacion entre ejercicios, 10 ejercicios por sesion',
        gymRoutineDays: 'Lunes: Pecho, Biceps, Hombro -Martes: Espalda, Triceps, y Trapecio -Miercoles: Pierna y Gluteo -Jueves: Pecho, Biceps y Antebrazo -Viernes: Espalda y Triceps -Sabado: Pierna, Gluteo, y Hombro'
    },
    {
        week: '20 Mayo',
        weekEnd: '26 Mayo',
        weekCount: '8/13',
        event: '',
        mesociclo: 'Pre-Competitivo',
        microciclo: 'CH',
        intensidad: '5 de 6',
        cardio: 'Interrumpido',
        cardioRoutine: '3 Rounds de 3" (15 trote moderado x 5" de intensidad), 1" de descaso entre rounds caminando, Completar tiempo restante',
        totalTime: '70',
        gym: 'Fuerza sub-maxima',
        gymRoutine: '4 series de 12 repeticiones al 80%, Fase positiva moderada, Fase negativa rapida, Alternar ejercicios (anterior - posterior),30 seg - 1 min de recuperacion entre series, 1 - 3 minutos de recuperacion entre ejercicios, 10 ejercicios por sesion',
        gymRoutineDays: 'Lunes: Pecho, Biceps, Hombro -Martes: Espalda, Triceps, y Trapecio -Miercoles: Pierna y Gluteo -Jueves: Pecho, Biceps y Antebrazo -Viernes: Espalda y Triceps -Sabado: Pierna, Gluteo, y Hombro'
    },
    {
        week: '27 Mayo',
        weekEnd: '2 Junio',
        weekCount: '9/13',
        event: '',
        mesociclo: 'Pre-Competitivo',
        microciclo: 'CH',
        intensidad: '6 de 6',
        cardio: 'Interrumpido',
        cardioRoutine: '3 Rounds de 3" (15 trote moderado x 5" de intensidad), 1" de descaso entre rounds caminando, Completar tiempo restante',
        totalTime: '70',
        gym: 'Fuerza explosiva',
        gymRoutine: '4 series de 12 repeticiones al 70%, Fase positiva rapida, Fase negativa moderada, Alternar ejercicios (anterior - posterior),30 seg de recuperacion entre series, 1 - 3 minutos de recuperacion entre ejercicios, 10 ejercicios por sesion',
        gymRoutineDays: 'Martes: Espalda, Triceps -Jueves: Pecho, Biceps y Hombro -Sabado: Pierna, Gluteo y Hombro'
    }
]
